server:
  port: 8080
#  servlet:
#    context-path: /api
#  compression:
#    enabled: true
#    mime-types: application/json,application/xml,text/html,text/xml,text/plain

spring:
#  security:
#    user:
#      name: admin
#      password: admin
  datasource:
    url: jdbc:h2:mem:universaldb
    driverClassName: org.h2.Driver
    username: sa
    password: ''

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
          order_inserts: true
          order_updates: true
        generate_statistics: true
    database-platform: org.hibernate.dialect.H2Dialect

  application:
    name: universal-service

jwt:
  secret: mySecretKey123sdfghjkjhgfdsdfghjklkjhgfdsdfgh
  expiration: 3600000  # 1 hour
  jwtCookieName : "universal-cookie"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /management
  endpoint:
    health:
      show-details: when-authorized
    metrics:
      enabled: true

logging:
  level:
    org.springframework: INFO
    org.hibernate: WARN
    com.universal: DEBUG
  file:
    name: logs/application.log
    max-size: 10MB
    max-history: 7
